### ISSUE TITLE
Construction fails when using default method

### ISSUE THREAD

**Issue by chippyash** [heminei/phpaes#1]
$aes = new AES();

result: The method is not available

Reason. Default method name is in upper case in constructor. 

 ```
   public function setMethod(string $method): self {
        if (!in_array($method, $this->getAvailableMethods())) {
            throw new \InvalidArgumentException("The method is not available");
        }
        $this->method = $method;
        return $this;
    }
```
the getAvailableMethods() function returns an array of methods in lower case. Hence, no match an exception thrown.

PHP 7.2 on Ubuntu Linux if it matters.

Suggest, use strtolower before test to ensure case compatibility.

Unit tests would have caught this btw.

**Comment by heminei** [comment]
Thanks for the report. The bug is fixed.
